
var teamTypes = [
  {
    "id": 1,
    "title": "瓦工班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 2,
    "title": "木工班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 3,
    "title": "钢筋班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 4,
    "title": "混凝土班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 5,
    "title": "油漆班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 6,
    "title": "防水班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 7,
    "title": "装饰装修",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 8,
    "title": "机械设备",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 9,
    "title": "架子班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 20678,
    "title": "外架租赁",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 20691,
    "title": "铝模班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 20692,
    "title": "普工班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 20693,
    "title": "铝合金班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 20694,
    "title": "石方爆破",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 20695,
    "title": "古建筑装饰",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 47007,
    "title": "园林绿化班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 48812,
    "title": "地基基础",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  }, {
    "id": 252753,
    "title": "墙体保温班",
    "regulation": null,
    "crafts": null,
    "quality": null,
    "category": {
      "id": "TUJIAN",
      "text": "土建",
      "category": "TEAM_CATEGORY",
      "groupTitle": null,
      "system": true,
      "orderIndex": 1,
      "oldId": null
    },
    "szTypeId": null,
    "msgIndex": 0,
    "libraryCount": 0,
    "status": 0,
    "orderIndex": 0
  },{
  "id": 10,
  "title": "电气设备",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 11,
  "title": "给排水班",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 12,
  "title": "消防安装",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 13,
  "title": "通风空调",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 14,
  "title": "弱电安装",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 15,
  "title": "燃气安装",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 16,
  "title": "电梯安装",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 17,
  "title": "钢结构安装",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20701,
  "title": "幕墙安装",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 75387,
  "title": "塔吊安拆",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 127943,
  "title": "水电班",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "ANZHUANG",
    "text": "安装",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 2,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 18,
  "title": "项目经理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 19,
  "title": "施工员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20,
  "title": "安全员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 21,
  "title": "资料员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20265,
  "title": "测量员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20696,
  "title": "造价员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20697,
  "title": "质量员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20698,
  "title": "材料员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20700,
  "title": "监理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 47096,
  "title": "工程师",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 74533,
  "title": "执行经理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 74534,
  "title": "生产经理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 74535,
  "title": "BIM技术员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 74536,
  "title": "商务经理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 83424,
  "title": "安全主任",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 83427,
  "title": "设备主管",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 83561,
  "title": "技术负责人",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 86581,
  "title": "财务管理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 99483,
  "title": "其他",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 99854,
  "title": "项目副经理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 136766,
  "title": "劳务管理员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 211968,
  "title": "建造师",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 211996,
  "title": "技术员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 212000,
  "title": "预算员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 219559,
  "title": "实验员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "GUANLI",
    "text": "管理",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 5,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20671,
  "title": "塔吊司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20672,
  "title": "塔吊指挥",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20673,
  "title": "吊车司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20674,
  "title": "司索工",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20675,
  "title": "电焊工",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20676,
  "title": "保安",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 20677,
  "title": "后勤",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 73423,
  "title": "劳务队",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 75723,
  "title": "电梯司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 76152,
  "title": "挖掘机司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 76382,
  "title": "专业分包",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 78717,
  "title": "电工",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 81294,
  "title": "破桩头",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 83668,
  "title": "喷锚工",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 83801,
  "title": "滚笼机工",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 84926,
  "title": "安装钳工",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 91979,
  "title": "铲车司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 100561,
  "title": "仓库管理",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 139018,
  "title": "保洁员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 171493,
  "title": "旋挖机司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 175313,
  "title": "电梯维修员",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}, {
  "id": 194380,
  "title": "压路机司机",
  "regulation": null,
  "crafts": null,
  "quality": null,
  "category": {
    "id": "QITA",
    "text": "其它  ",
    "category": "TEAM_CATEGORY",
    "groupTitle": null,
    "system": true,
    "orderIndex": 3,
    "oldId": null
  },
  "szTypeId": null,
  "msgIndex": 0,
  "libraryCount": 0,
  "status": 0,
  "orderIndex": 0
}];

module.exports = {
  teamTypes: teamTypes
}